### ISSUE TITLE
osdn.jp is very slow

### ISSUE THREAD

**Issue by hanayashiki** [pgbigm/pg_bigm#13]
I am trying to open `http://osdn.jp/projects/pgbigm/releases/?package_id=13634`. The site sometimes opens but takes like 1 minute to load.

**Comment by MasaoFujii** [comment]
@hanayashiki 
Yes, you're right.

Due to frequent access issues with OSDN, the pg_bigm site has been officially migrated to GitHub (i.e., this site).
