### ISSUE TITLE
Create a new release for Postgres 16 compatible version?

### ISSUE THREAD

**Issue by nozaq** [pgbigm/pg_bigm#14]
Hi there,

It seems https://github.com/pgbigm/pg_bigm/issues/10 is already fixed by https://github.com/pgbigm/pg_bigm/commit/34fe30fcb7dd58b6652e7cbf539f1615fcc0e47b and it's already back-ported to [REL1_2_STABLE](https://github.com/pgbigm/pg_bigm/tree/REL1_2_STABLE) branch.

Would it make sense to tag the current REL1_2_STABLE branch and create a new release with it?
I'm aware that the full migration to GitHub is still being planned, but making a new release at least provides people a stable package location with Postgres 16 support.

**Comment by MasaoFujii** [comment]
@nozaq 
Sorry for the delay.

I've just released the latest version of pg_bigm 1.2, now supporting PostgreSQL 16. The RPM files are not yet available but will be released later.

**Comment by nozaq** [comment]
@MasaoFujii 
Thank you! Just confirmed that v1.2-20240606 was successfully built with PostgresSQL 16 in my Docker environment 👍🏼
